# Original Concept Classes ICSE Library
# Content is original instructional material written for Concept Classes.
LIBRARY = {
 "9": {
  "Mathematics": [("Rational Numbers","Number systems, laws of exponents, rationalisation, and operations."),("Algebra","Identities, factorisation, linear equations and algebraic manipulation."),("Geometry","Core Euclidean ideas, angles, triangles, congruence and constructions."),("Mensuration","Perimeter, area, surface area and volume using unit-aware methods."),("Statistics","Collection, organisation and interpretation of data.")],
  "Physics": [("Measurements and Experimentation","Units, least count, significant figures and safe measurement practice."),("Motion","Distance, displacement, speed, velocity and acceleration with graphs."),("Laws of Motion","Force, inertia, momentum and Newton's laws."),("Gravitation","Mass, weight, gravity and basic applications."),("Work, Energy and Power","Work-energy idea, kinetic/potential energy and power.")],
  "Chemistry": [("The Language of Chemistry","Symbols, formulae, valency, equations and chemical calculations."),("Chemical Changes and Reactions","Signs of reaction, word equations and balancing."),("Water","Properties, solutions, purification and water of crystallisation."),("Atomic Structure","Particles, atomic number, mass number and electronic arrangement."),("The Periodic Table","Periods, groups and broad periodic trends.")],
  "Biology": [("Cell: The Unit of Life","Cell structure, organelles and differences between plant and animal cells."),("Tissues","Plant and animal tissues and their functions."),("The Flower","Parts of a flower, pollination and fertilisation."),("Human Nutrition","Digestive system, nutrients and balanced diet."),("Respiration","Aerobic/anaerobic respiration and energy release.")],
  "History & Civics": [("The Harappan Civilisation","Urban planning, society, economy, culture and sources."),("The Vedic Period","Early and later Vedic society, economy and institutions."),("Jainism and Buddhism","Origins, core teachings and historical significance."),("The Mauryan Empire","State, administration, Ashoka and sources."),("The Indian Constitution","Key constitutional ideas, rights and democratic institutions.")],
  "Geography": [("Our World","Earth as a planet, grid references and basic geographical tools."),("Structure of the Earth","Layers, rocks and internal processes."),("Atmosphere","Composition, structure, temperature and pressure."),("Hydrosphere","Water cycle, oceans and freshwater resources."),("Natural Vegetation","Factors controlling vegetation and conservation.")],
  "Computer Applications": [("Introduction to Java","Objects, classes, variables, data types and basic program structure."),("Operators and Expressions","Arithmetic, relational, logical operators and evaluation."),("Input and Output","Taking input, displaying output and simple calculations."),("Control Structures","Conditions, loops and tracing program flow."),("Methods","Breaking a program into reusable methods.")],
 },
 "10": {
  "Mathematics": [("Commercial Mathematics","GST, banking, recurring deposits, shares and financial calculations."),("Algebra","Quadratic equations, factorisation, progressions and algebraic reasoning."),("Coordinate Geometry","Distance, section formula, slope and coordinate applications."),("Geometry","Similarity, circles, constructions and proof-based reasoning."),("Trigonometry","Ratios, identities and heights-and-distances applications."),("Mensuration","Areas and volumes of solids and composite figures."),("Statistics and Probability","Central tendency, dispersion and elementary probability.")],
  "Physics": [("Force, Work, Power and Energy","Moments, work, energy, power and machines."),("Light","Reflection, refraction, lenses and image formation."),("Sound","Wave characteristics, resonance and practical applications."),("Electricity and Magnetism","Current, potential difference, resistance, circuits and magnetism."),("Heat","Calorimetry, heat transfer and changes of state."),("Modern Physics","Radioactivity and basic nuclear concepts.")],
  "Chemistry": [("Periodic Properties","Periodic trends and their explanation through electronic structure."),("Chemical Bonding","Electrovalent and covalent bonding and properties."),("Acids, Bases and Salts","Indicators, pH, reactions and salt preparation."),("Analytical Chemistry","Tests for common gases and ions."),("Organic Chemistry","Hydrocarbons, homologous series and important functional groups."),("Mole Concept and Stoichiometry","Relative masses, moles and equation-based calculations.")],
  "Biology": [("Cell Division","Mitosis, meiosis and their biological importance."),("Genetics","Genes, chromosomes, Mendelian ideas and inheritance."),("Plant Physiology","Photosynthesis, transpiration and transport."),("Human Circulatory System","Blood, heart, vessels and circulation."),("Human Nervous System","Neurons, brain, spinal cord and coordination."),("Reproductive System","Human reproduction, menstrual cycle and reproductive health.")],
  "History & Civics": [("The Union Legislature","Parliament, law-making and major constitutional roles."),("The Union Executive","President, Prime Minister and Council of Ministers."),("The Judiciary","Supreme Court, judicial review and independence of judiciary."),("The First War of Independence","Causes, course, nature and consequences."),("Indian National Movement","Major developments from the late nineteenth century to independence."),("The United Nations","Purpose, principal organs and India's role.")],
  "Geography": [("Climate","Factors, monsoon mechanism, seasons and rainfall patterns."),("Soils","Major soil types, formation, distribution and conservation."),("Natural Vegetation","Forest types, distribution, uses and conservation."),("Water Resources","Irrigation, multipurpose projects and water management."),("Mineral and Energy Resources","Minerals, conventional and non-conventional energy."),("Agriculture","Major crops, conditions, production patterns and challenges."),("Industries","Industrial location, major industries and environmental concerns."),("Transport and Waste Management","Transport networks and principles of sustainable waste management.")],
  "Computer Applications": [("Class and Object","Object-oriented thinking, classes, objects and constructors."),("Methods","Parameters, return values, overloading and modular programming."),("Library Classes","String, wrapper and mathematical library methods."),("Arrays","One-dimensional and two-dimensional arrays and traversal."),("String Handling","Common String methods and character processing."),("Inheritance and Polymorphism","Core OOP relationships and method overloading.")],
  "English Language": [("Composition","Planning, structure, paragraphing, vocabulary and revision."),("Letter Writing","Formal/informal purpose, format, tone and clarity."),("Notice and Email","Concise information, audience awareness and correct format."),("Comprehension","Finding evidence, inference, vocabulary and precise answers."),("Grammar","Agreement, tenses, clauses, prepositions, transformation and editing.")]
 }
}
def get_library():
    return LIBRARY
